#ifndef VKRT_SHARED_CONSTANTS_H
#define VKRT_SHARED_CONSTANTS_H

#define VKRT_SCENE_TIMELINE_MAX_KEYFRAMES 16u

#define VKRT_MAX_ABSORPTION_COEFFICIENT 1000000.0f

#define VKRT_TONE_MAPPING_MODE_NONE 0u
#define VKRT_TONE_MAPPING_MODE_ACES 1u
#define VKRT_TONE_MAPPING_MODE_COUNT 2u

#define VKRT_DEBUG_MODE_NONE 0u
#define VKRT_DEBUG_MODE_NORMALS 1u
#define VKRT_DEBUG_MODE_DEPTH 2u
#define VKRT_DEBUG_MODE_BOUNCE_COUNT 3u
#define VKRT_DEBUG_MODE_NEE_ONLY 4u
#define VKRT_DEBUG_MODE_BSDF_ONLY 5u
#define VKRT_DEBUG_MODE_SELECTION_MASK 6u
#define VKRT_DEBUG_MODE_BASE_COLOR_MAP 7u
#define VKRT_DEBUG_MODE_METALLIC_MAP 8u
#define VKRT_DEBUG_MODE_ROUGHNESS_MAP 9u
#define VKRT_DEBUG_MODE_NORMAL_MAP 10u
#define VKRT_DEBUG_MODE_EMISSIVE_MAP 11u
#define VKRT_DEBUG_MODE_COUNT 12u

#define VKRT_INVALID_INDEX 0xFFFFFFFFu

#define VKRT_MATERIAL_ALPHA_MODE_OPAQUE 0u
#define VKRT_MATERIAL_ALPHA_MODE_MASK 1u
#define VKRT_MATERIAL_ALPHA_MODE_BLEND 2u

#define VKRT_TEXTURE_COLOR_SPACE_SRGB 0u
#define VKRT_TEXTURE_COLOR_SPACE_LINEAR 1u
#define VKRT_TEXTURE_COLOR_SPACE_COUNT 2u

#define VKRT_MAX_BINDLESS_TEXTURES 1024u

#define VKRT_MATERIAL_TEXTURE_SLOT_BASE_COLOR 0u
#define VKRT_MATERIAL_TEXTURE_SLOT_METALLIC_ROUGHNESS 1u
#define VKRT_MATERIAL_TEXTURE_SLOT_NORMAL 2u
#define VKRT_MATERIAL_TEXTURE_SLOT_EMISSIVE 3u
#define VKRT_MATERIAL_TEXTURE_SLOT_COUNT 4u

#define VKRT_TEXTURE_WRAP_REPEAT 10497u
#define VKRT_TEXTURE_WRAP_CLAMP_TO_EDGE 33071u
#define VKRT_TEXTURE_WRAP_MIRRORED_REPEAT 33648u
#define VKRT_TEXTURE_SAMPLER_VARIANT_COUNT 9u
#define VKRT_TEXTURE_WRAP_DEFAULT (VKRT_TEXTURE_WRAP_REPEAT | (VKRT_TEXTURE_WRAP_REPEAT << 16u))

#endif
