#ifndef VKRT_SHARED_CONSTANTS_H
#define VKRT_SHARED_CONSTANTS_H

#define VKRT_SCENE_TIMELINE_MAX_KEYFRAMES 16u

#define VKRT_NAME_LEN 256

#define VKRT_TONE_MAPPING_MODE_NONE 0u
#define VKRT_TONE_MAPPING_MODE_ACES 1u

#define VKRT_DEBUG_MODE_NONE 0u
#define VKRT_DEBUG_MODE_NORMALS 1u
#define VKRT_DEBUG_MODE_DEPTH 2u
#define VKRT_DEBUG_MODE_BOUNCE_COUNT 3u
#define VKRT_DEBUG_MODE_NEE_ONLY 4u
#define VKRT_DEBUG_MODE_BSDF_ONLY 5u
#define VKRT_DEBUG_MODE_SELECTION_MASK 6u
#define VKRT_DEBUG_MODE_FRESNEL 7u
#define VKRT_DEBUG_MODE_COUNT 8u

#define VKRT_INVALID_INDEX 0xFFFFFFFFu

#endif
