#ifndef VKRT_SHARED_TEXTURE_FORMATS_H
#define VKRT_SHARED_TEXTURE_FORMATS_H

#include <stdint.h>

typedef uint32_t VKRT_TextureFormat;

enum {
    VKRT_TEXTURE_FORMAT_RGBA8_UNORM = 0u,
    VKRT_TEXTURE_FORMAT_RGBA16_UNORM = 1u,
    VKRT_TEXTURE_FORMAT_RGBA16_SFLOAT = 2u,
    VKRT_TEXTURE_FORMAT_RGBA32_SFLOAT = 3u,
    VKRT_TEXTURE_FORMAT_COUNT = 4u,
};

#endif
