#ifndef VKRT_GGX_ENERGY_H
#define VKRT_GGX_ENERGY_H

#define VKRT_GGX_ENERGY_ROUGHNESS_SIZE  32u
#define VKRT_GGX_ENERGY_COSINE_SIZE     80u
#define VKRT_GGX_ENERGY_GRAZING_SIZE    48u
#define VKRT_GGX_ENERGY_IOR_SIZE        128u
#define VKRT_GGX_ENERGY_ANISOTROPY_SIZE 9u
#define VKRT_GGX_ENERGY_AZIMUTH_SIZE    9u
#define VKRT_GGX_ENERGY_ANGULAR_SIZE    (VKRT_GGX_ENERGY_ROUGHNESS_SIZE * VKRT_GGX_ENERGY_COSINE_SIZE)
#define VKRT_GGX_ENERGY_REFLECTION_SIZE \
    (VKRT_GGX_ENERGY_ANGULAR_SIZE * VKRT_GGX_ENERGY_ANISOTROPY_SIZE * VKRT_GGX_ENERGY_AZIMUTH_SIZE)
#define VKRT_GGX_ENERGY_AVERAGE_OFFSET (2u * VKRT_GGX_ENERGY_REFLECTION_SIZE)
#define VKRT_GGX_ENERGY_GLASS_OFFSET \
    (VKRT_GGX_ENERGY_AVERAGE_OFFSET + VKRT_GGX_ENERGY_ROUGHNESS_SIZE * VKRT_GGX_ENERGY_ANISOTROPY_SIZE)
#define VKRT_GGX_ENERGY_GLASS_SIZE (VKRT_GGX_ENERGY_REFLECTION_SIZE * VKRT_GGX_ENERGY_IOR_SIZE)
#define VKRT_GGX_ENERGY_COUNT      (VKRT_GGX_ENERGY_GLASS_OFFSET + 2u * VKRT_GGX_ENERGY_GLASS_SIZE)

#endif
