#ifndef VKRT_BSDF_COMMON_SLANG
#define VKRT_BSDF_COMMON_SLANG

#include "../camera/ray.slang"
#include "../sampling/random.slang"
#include "../utility/color.slang"
#include "../utility/spectral.slang"
#include "./base/basis.slang"
#include "./base/fresnel.slang"
#include "./base/interface.slang"
#include "./base/material.slang"
#include "./base/math.slang"
#include "./base/medium.slang"
#include "./types.slang"

#endif
